services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_JOBS_DB_PW}
      POSTGRES_DB: ${PG_JOBS_DB_DATABASE}
    ports:
      - '${PG_JOBS_DB_PORT}:${PG_JOBS_DB_PORT}'
    volumes:
    - database:/var/lib/postgresql/data
    - ./docker-init/postgres:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  job_executor:
    image: runway_executor
    container_name: job-executor
    # restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEPLOYMENT_MODE: LOCAL 
      INIT_TOKEN: ${INIT_TOKEN}
      INIT_JOB_URL: ${INIT_JOB_URL}
    entrypoint: python -u /executor/scripts/main.py
    volumes:
      - ./storage:/storage
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
  
  app:
    image: node
    container_name: nodejs_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEPLOYMENT_MODE: LOCAL
      PG_JOBS_DB_HOST: ${PG_JOBS_DB_HOST}
      PG_JOBS_DB_PORT: ${PG_JOBS_DB_PORT}
      PG_JOBS_DB_DATABASE: ${PG_JOBS_DB_DATABASE}
      PG_JOBS_DB_USER: ${PG_JOBS_DB_USER}
      PG_JOBS_DB_PW: ${PG_JOBS_DB_PW}
      PG_JOBS_DB_PW_SECRET: ${PG_JOBS_DB_PW_SECRET}
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/home/node/app
      - ./app/node_modules:/home/node/app/node_modules
      - ./storage:/storage
    command: node /home/node/app/index.js

volumes:
   database:
