services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.0
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
  keycloak-config:
    image: adorsys/keycloak-config-cli:latest-21.0.1
    depends_on:
      - keycloak
    volumes:
      - ./keycloak/:/config
    environment:
      KEYCLOAK_URL: http://keycloak:8080/
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 60s
      IMPORT_FILES: '/config/*'
      IMPORT_MANAGED_GROUP: no-delete
      IMPORT_MANAGED_REQUIREDACTION: no-delete
      IMPORT_MANAGED_CLIENTSCOPE: no-delete
      IMPORT_MANAGED_SCOPEMAPPING: no-delete
      IMPORT_MANAGED_CLIENTSCOPEMAPPING: no-delete
      IMPORT_MANAGED_ROLE: no-delete
      IMPORT_MANAGED_COMPONENT: no-delete
      IMPORT_MANAGED_SUBCOMPONENT: no-delete
      IMPORT_MANAGED_AUTHENTICATIONFLOW: no-delete
      IMPORT_MANAGED_IDENTITYPROVIDER: no-delete
      IMPORT_MANAGED_IDENTITYPROVIDERMAPPER: no-delete
      IMPORT_MANAGED_CLIENT: no-delete
      IMPORT_MANAGED_CLIENTAUTHORIZATIONRESOURCES: no-delete
      IMPORT_MANAGED_CLIENTAUTHORIZATIONPOLICIES: no-delete
      IMPORT_MANAGED_CLIENTAUTHORIZATIONSCOPES: no-delete
      IMPORT_MANAGED_MESSAGEBUNDLES: no-delete

volumes:
  database:
